# Generated by Django 4.2.4 on 2023-10-20 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('image', models.ImageField(upload_to='')),
                ('description', models.TextField(max_length=1500)),
                ('time', models.IntegerField(default=0)),
                ('complexity', models.IntegerField(choices=[('0', 'Легко'), ('1', 'Нормально'), ('3', 'Складно')])),
                ('portions', models.IntegerField(default=0)),
                ('video_url', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('count', models.IntegerField(default=0)),
                ('variable', models.IntegerField(choices=[('кілограм', 'кг'), ('грам', 'г'), ('літр', 'л'), ('мілілітр', 'мл'), ('штук', 'шт'), ('чайна ложка', 'ч.л'), ('столова ложка', 'ст.л')])),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.dish')),
            ],
        ),
    ]
