# Generated by Django 4.2.4 on 2023-10-20 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='complexity',
            field=models.IntegerField(choices=[('Легко', 'Легко'), ('Нормально', 'Нормально'), ('Складно', 'Складно')]),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='variable',
            field=models.IntegerField(choices=[('кг', 'кг'), ('г', 'г'), ('л', 'л'), ('мл', 'мл'), ('шт', 'шт'), ('ч.л', 'ч.л'), ('ст.л', 'ст.л')]),
        ),
    ]
